#JSON Schema for the entire residential building.

scenario_schema = {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "EvacuationScenarioObject",
    "type": "object",
    "required": ["schema_version", "provenance", "building", "exits", "spaces",
                 "scenarios", "validation", "not_assessed"],
    "properties": {
        "schema_version": {"type": "string"},
        "model": {
            "type": "object",
            "required": ["units"],
            "properties": {
                "source_ifc": {"type": ["string", "null"]},
                "units": {"type": "string"},
                "coordinate_system": {"type": "string"},
                "geometry_note": {"type": "string"},
            },
        },
        "provenance": {
            "type": "object",
            "required": ["generated_by_model", "distance_method", "llm_grounded"],
            "properties": {
                "generated_by_model": {"type": ["string", "null"]},
                "generated_at": {"type": "string"},
                "occupancy_factor_source": {"type": "string"},
                "distance_method": {"type": "string"},
                "llm_grounded": {"type": "boolean"},
                "llm_temperature": {"type": ["string", "number", "null"]},
            },
        },
        "building": {
            "type": "object",
            "required": ["project", "storeys", "total_floor_area_m2", "total_occupant_load"],
            "properties": {
                "project": {"type": ["string", "null"]},
                "source_ifc": {"type": ["string", "null"]},
                "jurisdiction": {"type": "string"},
                "occupancy_type": {"type": "string"},
                "storeys": {"type": "integer", "minimum": 0},
                "total_floor_area_m2": {"type": "number", "minimum": 0},
                "total_occupant_load": {"type": "integer", "minimum": 0},
            },
        },
        "exits": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["id"],
                "properties": {
                    "id": {"type": "string"},
                    "exit_name": {"type": ["string", "null"]},
                    "name": {"type": ["string", "null"]},
                    "type": {"type": "string"},
                    "width_m": {"type": ["number", "null"]},
                    "position": {"type": ["array", "null"]},
                },
            },
        },
        "doors": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["id"],
                "properties": {
                    "id": {"type": "string"},
                    "name": {"type": ["string", "null"]},
                    "type": {"type": "string"},
                    "width_m": {"type": ["number", "null"]},
                    "position": {"type": ["array", "null"]},
                    "connects": {"type": "array", "items": {"type": "string"}},
                },
            },
        },
        "circulation": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["id"],
                "properties": {
                    "id": {"type": "string"},
                    "name": {"type": ["string", "null"]},
                    "type": {"type": "string"},
                    "width_m": {"type": ["number", "null"]},
                    "width_source": {"type": ["string", "null"]},
                    "position": {"type": ["array", "null"]},
                    "rise_m": {"type": ["number", "null"]},
                    "going_m": {"type": ["number", "null"]},
                    "slope_m": {"type": ["number", "null"]},
                    "connects_storeys": {"type": "array", "items": {"type": "string"}},
                },
            },
        },
        "stair_links": {"type": "array"},
        "elevators": {"type": "array"},
        "spaces": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["guid", "use_type", "reachable"],
                "properties": {
                    "guid": {"type": "string"},
                    "name": {"type": ["string", "null"]},
                    "use_type": {"type": "string"},
                    "use_type_confidence": {"type": ["number", "null"]},
                    "use_type_source": {"type": ["string", "null"]},
                    "storey": {"type": ["string", "null"]},
                    "area_m2": {"type": ["number", "null"]},
                    "centroid": {"type": ["array", "null"]},
                    "occupant_load": {"type": ["integer", "null"], "minimum": 0},
                    "occupant_basis": {"type": ["string", "null"]},
                    "nearest_exit": {"type": ["string", "null"]},
                    "nearest_exit_name": {"type": ["string", "null"]},
                    "travel_distance_m": {"type": ["number", "null"], "minimum": 0},
                    "travel_distance_method": {"type": ["string", "null"]},
                    "most_remote_point": {"type": ["array", "null"]},
                    "reachable": {"type": "boolean"},
                    "reachability_note": {"type": ["string", "null"]},
                },
            },
        },
        "degraded_cases": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["exit_discounted", "per_storey"],
                "properties": {
                    "exit_discounted": {"type": "string"},
                    "exit_discounted_name": {"type": ["string", "null"]},
                    "method": {"type": "string"},
                    "per_storey": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "storey": {"type": ["string", "null"]},
                                "occupants": {"type": "integer", "minimum": 0},
                                "max_travel_distance_m": {"type": ["number", "null"], "minimum": 0},
                                "unreachable": {"type": "integer", "minimum": 0},
                            },
                        },
                    },
                },
            },
        },
        "scenarios": {
            "type": "array",
            "minItems": 2,
            "items": {
                "type": "object",
                "required": ["id", "type", "scenario_objective", "evacuation_routes", "narrative"],
                "properties": {
                    "id": {"type": "string"},
                    "type": {"type": "string"},
                    "title": {"type": "string"},
                    "scenario_objective": {
                        "type": "object",
                        "required": ["conditions"],
                        "properties": {
                            "purpose": {"type": "string"},
                            "conditions": {
                                "type": "object",
                                "required": ["exits_discounted"],
                                "properties": {
                                    "exits_discounted": {"type": "array",
                                                         "items": {"type": "string"}},
                                    "exits_discounted_ifc_ids": {"type": "array",
                                                                 "items": {"type": "string"}},
                                },
                            },
                        },
                    },
                    "evacuation_routes": {
                        "type": "object",
                        "required": ["exits_available", "routes"],
                        "properties": {
                            "exits_available": {"type": "array", "items": {"type": "string"}},
                            "exits_available_ifc_ids": {"type": "array",
                                                        "items": {"type": "string"}},
                            "routes": {"type": "array"},
                            "restricted_areas": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "required": ["area", "reason"],
                                    "properties": {
                                        "area": {"type": "string"},
                                        "reason": {"type": "string"},
                                    },
                                },
                            },
                        },
                    },
                    "assumptions": {"type": "array"},
                    "occupant_distribution": {"type": "array"},
                    "bottlenecks": {"type": "array"},
                    "risks": {"type": "array"},
                    "narrative": {"type": "string"},
                    "fire_conditions": {
                        "type": "object",
                        "required": ["fire_origin", "detection_and_alarm", "smoke_conditions"],
                        "properties": {
                            "fire_origin": {"type": "string"},
                            "fire_origin_storey": {"type": "string"},
                            "affected_exits": {"type": "array", "items": {"type": "string"}},
                            "affected_routes": {"type": "array", "items": {"type": "string"}},
                            "detection_and_alarm": {"type": "string"},
                            "smoke_conditions": {"type": "string"},
                            "basis": {"type": "string"},
                        },
                    },
                    "simulation": {
                        "type": "object",
                        "required": ["movement_model", "simulation_settings", "pre_movement",
                                     "profiles", "evacuation_time"],
                        "properties": {
                            "movement_model": {"type": "string"},
                            "simulation_settings": {
                                "type": "object",
                                "required": ["start_conditions", "duration"],
                                "properties": {
                                    "start_conditions": {"type": "string"},
                                    "duration": {
                                        "type": "object",
                                        "required": ["seconds"],
                                        "properties": {
                                            "seconds": {"type": "number", "minimum": 0},
                                            "basis": {"type": "string"},
                                        },
                                    },
                                },
                            },
                            "evacuation_time": {
                                "type": "object",
                                "required": ["estimated_total_s"],
                                "properties": {
                                    "estimated_total_s": {"type": "number", "minimum": 0},
                                    "basis": {"type": "string"},
                                },
                            },
                            "pre_movement": {
                                "type": "object",
                                "required": ["response_delay"],
                                "properties": {
                                    "detection": {"type": "string"},
                                    "alarm": {"type": "string"},
                                    "recognition": {"type": "string"},
                                    "response_delay": {
                                        "type": "object",
                                        "required": ["distribution", "mean_s", "basis"],
                                        "properties": {
                                            "distribution": {"type": "string"},
                                            "mean_s": {"type": "number", "minimum": 0},
                                            "sd_s": {"type": "number", "minimum": 0},
                                            "basis": {"type": "string"},
                                        },
                                    },
                                },
                            },
                            "profiles": {
                                "type": "array",
                                "minItems": 1,
                                "items": {
                                    "type": "object",
                                    "required": ["name", "fraction", "speed_ms_mean",
                                                 "shoulder_width_m", "basis"],
                                    "properties": {
                                        "name": {"type": "string"},
                                        "fraction": {"type": "number", "minimum": 0, "maximum": 1},
                                        "speed_distribution": {"type": "string"},
                                        "speed_ms_mean": {"type": "number", "minimum": 0},
                                        "speed_ms_sd": {"type": "number", "minimum": 0},
                                        "shoulder_width_m": {"type": "number", "minimum": 0},
                                        "basis": {"type": "string"},
                                    },
                                },
                            },
                            "occupancy_multipliers": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "required": ["use_type", "multiplier"],
                                    "properties": {
                                        "use_type": {"type": "string"},
                                        "multiplier": {"type": "number", "minimum": 0, "maximum": 1},
                                        "reason": {"type": "string"},
                                    },
                                },
                            },
                        },
                    },
                    "occupancy": {
                        "type": "object",
                        "properties": {
                            "occupants_total": {"type": ["integer", "null"], "minimum": 0},
                            "occupancy_state": {"type": ["string", "null"]},
                            "occupancy_state_label": {"type": ["string", "null"]},
                            "placed_total": {"type": "integer", "minimum": 0},
                            "unplaced_total": {"type": "integer", "minimum": 0},
                            "unallocated_total": {"type": "integer", "minimum": 0},
                            "unallocated_why": {"type": ["string", "null"]},
                            "scenario_room_capacity": {"type": "integer", "minimum": 0},
                            "building_computed_total": {"type": ["integer", "null"], "minimum": 0},
                            "allocation_method": {"type": "string"},
                            "position_note": {"type": "string"},
                            "by_room": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "required": ["guid", "occupants", "goal"],
                                    "properties": {
                                        "guid": {"type": "string"},
                                        "name": {"type": ["string", "null"]},
                                        "storey": {"type": ["string", "null"]},
                                        "use_type": {"type": ["string", "null"]},
                                        "computed_occupant_load": {"type": ["integer", "null"],
                                                                   "minimum": 0},
                                        "occupants": {"type": "integer", "minimum": 1},
                                        "seed_point": {"type": ["array", "null"]},
                                        "profiles": {"type": "object"},
                                        "goal": {"type": "string"},
                                        "goal_exit": {"type": ["string", "null"]},
                                    },
                                },
                            },
                            "unplaced_rooms": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "required": ["guid", "occupants_not_placed", "why"],
                                    "properties": {
                                        "guid": {"type": "string"},
                                        "name": {"type": ["string", "null"]},
                                        "storey": {"type": ["string", "null"]},
                                        "use_type": {"type": ["string", "null"]},
                                        "computed_occupant_load": {"type": ["integer", "null"],
                                                                   "minimum": 0},
                                        "occupants_not_placed": {"type": "integer", "minimum": 1},
                                        "why": {"type": "string"},
                                    },
                                },
                            },
                            "rerouted_rooms": {
                                "type": "object",
                                "properties": {
                                    "count": {"type": "integer", "minimum": 0},
                                    "guids": {"type": "array", "items": {"type": "string"}},
                                    "why": {"type": "string"},
                                },
                            },
                        },
                    },
                    "occupancy_rationale": {"type": "string"},
                    "regulatory_justification": {"type": "string"},
                    "ai_explanation": {"type": "string"},
                },
            },
        },
        "regulation_check": {
            "type": "object",
            "required": ["passed"],
            "properties": {
                "jurisdiction": {"type": "string"},
                "passed": {"type": "boolean"},
                "basis": {"type": "string"},
                "violations": {"type": "array"},
                "manual_review": {"type": "array"},
            },
        },
        "validation": {"type": "object"},
        "not_assessed": {"type": "array"},
    },
}
